name: "Update PR Status Labels"
description: "Update the labels of a PR, depending on its review status"
inputs:
  one-approval-label-name:
    description: "Name of the label to show when the PR has one approval"
    required: true
    default: "1 approval"
  two-approvals-label-name:
    description: "Name of the label to show when the PR has two approvals"
    required: true
    default: "2 approvals"
  changes-requested-label-name:
    description: "Name of the label to show when the PR needs changes"
    required: true
    default: "needs updating"
  updated-pr-label-name:
    description: "Name of the label to show when the PR has been updated"
    required: true
    default: "updated"
runs:
  using: "node16"
  main: "index.js"
branding:
  icon: "git-pull-request"
  color: "red"
